import Head from "next/head";
import Image from "next/image";
//import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import About from "@/components/About";
import Service from "@/components/Service";
import Feature from "@/components/Feature";
import Team from "@/components/Team";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Consultorio Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <About />
        <Service />
        <Feature />
        <Team />
      </main>
    </>
  );
}
